# Generated by Django 4.0.5 on 2022-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_review_blog_alter_review_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
