# Generated by Django 4.0.5 on 2022-07-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
    ]
